/**
 * AUTO-GENERATED by frontend/scripts/gen-api-types.mjs
 * Source: docs/api-specs/pipeline.openapi.json
 * DO NOT EDIT BY HAND — run `npm run gen:api` after the BE spec changes.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Analysis
         * @description Create an analysis_run (multi-template batch) and emit pipeline.silver.complete
         *     so the ai-orchestrator picks it up.
         *
         *     Validation: UUID-typed inputs return 422 on malformed values.
         */
        post: operations["trigger_analysis_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clean/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Cleaning Rules
         * @description Apply selected cleaning rules to Bronze → write Silver. ASYNC: validate,
         *     then return 202 and run the heavy rule-application + Silver write (tens of
         *     thousands of rows across sheets — synchronously it blew the gateway 30s
         *     → 504) in a BackgroundTask. Poll GET /upload/{run_id}/status until
         *     'silver_complete' or 'failed'. K-2: Bronze rows never modified.
         *
         *     Validation: UUID-typed inputs return 422 on malformed values.
         */
        post: operations["apply_cleaning_rules_clean_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clean/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Cleaning Suggestions
         * @description Return applicable cleaning rules based on detected schema.
         *
         *     CR-0016 closeout: when DERIVE_LINE_TOTAL applies, attach MEASURED amount
         *     signals + a suggestion (presence-based, no forced threshold) so the user
         *     approves the unit-price × quantity derivation with the evidence in view.
         *
         *     Validation: UUID-typed run_id / file_id / X-Enterprise-ID return 422 on
         *     malformed values.
         */
        post: operations["get_cleaning_suggestions_clean_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/bronze/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bronze Files
         * @description List bronze files for the calling tenant, newest first.
         *
         *     Each row joins ``bronze_files`` (per-sheet metadata) with the parent
         *     ``pipeline_runs`` (the upload that produced it) so the FE can show
         *     "X.csv → Sheet1 (1,200 rows)" without a second round-trip.
         */
        get: operations["list_bronze_files_data_bronze_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/bronze/files/{file_id}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Bronze File
         * @description Sample N rows from a bronze file (default 50, max 200).
         *
         *     K-2 — bronze_rows is append-only and contains the raw upload as
         *     JSONB. We return the first ``limit`` rows ordered by ``row_index``;
         *     the FE renders them as a table where columns are inferred from the
         *     JSON keys of the first row.
         */
        get: operations["sample_bronze_file_data_bronze_files__file_id__sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/explorer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Explorer Snapshot
         * @description One-shot snapshot for the /p2/data hub.
         *
         *     Each layer block is a single small SQL — bronze + silver + gold all
         *     use indexed enterprise_id columns. The recent-activity strip shares
         *     the pipeline_runs index. Total cost is well under the 50ms p95
         *     budget for a hub page.
         */
        get: operations["get_explorer_snapshot_data_explorer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/gold/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gold Customers
         * @description List gold_features for the tenant — analyst browse view.
         *
         *     Note this is the *all customers* version. /api/v1/customers/at-risk
         *     (F-060) is the focused HIGH-risk slice with extra revenue tile +
         *     action toggle; this endpoint is for "show me everything in gold"
         *     so analysts can validate the aggregator output.
         */
        get: operations["list_gold_customers_data_gold_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lineage
         * @description Trace one bronze file through Silver and Gold.
         *
         *     Bronze: file + parent run metadata (always present if 404 doesn't fire).
         *     Silver: aggregate of silver_rows for this file + applied_rules
         *              top-3 (null when the file has never been cleaned).
         *     Gold:   best-effort COUNT DISTINCT customer_external_id seen in
         *              this file's silver row_data → how many gold_features
         *              rows this file contributes to. Null when the silver
         *              row_data doesn't carry the canonical customer key
         *              (per MEDALLION_CONTRACT.md the tenant must onboard with
         *              that mapping; older pipelines may not have it).
         */
        get: operations["get_lineage_data_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/silver/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Silver Datasets
         * @description List silver datasets (group of silver_rows per file) for the tenant.
         *
         *     Each row aggregates ``silver_rows`` and joins ``bronze_files`` +
         *     ``pipeline_runs`` so the FE shows the cleaned-rows count alongside
         *     the source filename and the average quality score.
         */
        get: operations["list_silver_datasets_data_silver_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/silver/datasets/{file_id}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Silver Dataset
         * @description Sample N cleaned rows from a silver dataset (default 50, max 200).
         *
         *     K-5 — silver_rows.row_data already has PII redacted by the
         *     cleaning pipeline. We never re-mask here; the source of truth is
         *     what the cleaning step wrote.
         */
        get: operations["sample_silver_dataset_data_silver_datasets__file_id__sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pipelines
         * @description List pipeline runs for the calling tenant, newest first.
         */
        get: operations["list_pipelines_pipelines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Stream
         * @description Server-Sent Events for a single pipeline run.
         *
         *     Emits one event per ``pipeline_runs.status`` transition for the run.
         *     Heartbeats every 15 s as comment lines so reverse proxies (nginx,
         *     AWS ALB) don't close the idle TCP connection. Browsers reconnect
         *     automatically with ``Last-Event-ID`` — when present, we replay the
         *     current row state immediately so the client sees the latest known
         *     status without having to wait for the next transition.
         */
        get: operations["status_stream_pipelines__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-mining/connectors/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Calendar
         * @description Register a Calendar metadata connector for this tenant.
         */
        post: operations["register_calendar_process_mining_connectors_calendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-mining/connectors/generic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Generic Webhook
         * @description PM-EVT-008 — generic webhook event-log connector. Tenants register
         *     the mapping config; the actual webhook receiver endpoint (POST
         *     /process-mining/webhook/{label}) routes payloads here for mapping.
         */
        post: operations["register_generic_webhook_process_mining_connectors_generic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-mining/connectors/gmail-outlook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Gmail Outlook
         * @description Register a Gmail / Outlook metadata connector for this tenant.
         *
         *     Validates channel + mailbox via the connector's own __init__ so any
         *     misconfig surfaces as 422 immediately. Returns a session_id that
         *     the worker uses as cursor key. Real polling fires when the
         *     `TEMPORAL_ENABLE_WORKER=true` flag is set (default false P15-S10).
         */
        post: operations["register_gmail_outlook_process_mining_connectors_gmail_outlook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-mining/connectors/microsoft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Microsoft Sharepoint
         * @description PM-EVT-007 — MS SharePoint file change connector via MS Graph
         *     delta query.
         */
        post: operations["register_microsoft_sharepoint_process_mining_connectors_microsoft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-mining/connectors/slack-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Slack Teams
         * @description PM-EVT-006 — Slack Enterprise Grid / Teams audit-API connector.
         *
         *     Validates channel + workspace via the connector's __init__. Real
         *     polling fires when TEMPORAL_ENABLE_WORKER=true AND the per-tenant
         *     OAuth onboarding completes (the Slack admin / Teams Tenant Admin
         *     consent ships outside this endpoint).
         */
        post: operations["register_slack_teams_process_mining_connectors_slack_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Get all analysis results for a pipeline run.
         *
         *     Validation: UUID-typed run_id and X-Enterprise-ID return 422 on
         *     malformed values.
         */
        get: operations["get_results_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Schema
         * @description Detect canonical schema for a pipeline run.
         *     Returns column mappings with confidence scores + uncertainty flags.
         *
         *     Validation: req.run_id and X-Enterprise-ID are typed as UUID — Pydantic +
         *     FastAPI return 422 automatically on malformed values.
         */
        post: operations["get_schema_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Schema
         * @description User confirms (and optionally overrides) column mappings.
         *     Saves to canonical_schemas table.
         *
         *     Validation: UUID-typed inputs return 422 on malformed values.
         */
        post: operations["confirm_schema_schema_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Canonical Fields */
        get: operations["list_canonical_fields_schema_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a data file (Excel, CSV, ODS, ZIP, SQL).
         *
         *     Two paths:
         *       • **Workflow-card attach** (X-Workflow-Step-ID set) → SYNCHRONOUS. These
         *         carry the required_document_types whitelist (must reject wrong-kind
         *         before the dedup short-circuit) and are typically small docs. Returns
         *         the full ingest result, as before.
         *       • **Basic data upload** (no X-Workflow-Step-ID) → ASYNC. A large workbook
         *         (parse + detect + Bronze write) can exceed the gateway timeout, so we
         *         return 202 {run_id, status:'uploading'} immediately and ingest in a
         *         BackgroundTask. Poll GET /upload/{run_id}/status until 'bronze_complete'
         *         / 'silver_complete' / 'unstructured_pending' / 'failed'.
         *
         *     Idempotent (K-8): same file hash + enterprise → existing non-failed run_id
         *     is reused (async path checks before spawning; sync path checks inside
         *     ingest_file). Cross-tenant guard: a supplied ID not in the enterprise → 400.
         */
        post: operations["upload_file_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload Status
         * @description Poll pipeline run status. Frontend polls every 2s until status =
         *     'bronze_complete' or 'failed'.
         *
         *     Validation: malformed run_id or X-Enterprise-ID returns 422 from
         *     FastAPI's path/header parser before hitting the handler.
         */
        get: operations["get_upload_status_upload__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Consent External Ai
             * @default false
             */
            consent_external_ai: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Templates */
            templates: string[];
        };
        /** ApplyRulesRequest */
        ApplyRulesRequest: {
            /** Rule Ids */
            rule_ids: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** Body_upload_file_upload_post */
        Body_upload_file_upload_post: {
            /** File */
            file: string;
        };
        /** CalendarRegisterRequest */
        CalendarRegisterRequest: {
            /**
             * Channel
             * @description 'google_calendar' or 'outlook_calendar'
             */
            channel: string;
            /** Oauth Credential Path */
            oauth_credential_path?: string | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
            /**
             * Tenant Calendar Id
             * @description Calendar id ('primary' for default user calendar)
             */
            tenant_calendar_id: string;
            /**
             * Tenant Mailbox
             * @description Calendar owner email (OAuth principal)
             */
            tenant_mailbox: string;
        };
        /** CleanSuggestRequest */
        CleanSuggestRequest: {
            /** File Id */
            file_id?: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ConnectorRegisterResponse
         * @description Response shape for both endpoints. session_id is a stable handle
         *     that the Temporal Process Mining worker uses for cursor state.
         */
        ConnectorRegisterResponse: {
            /** Channel */
            channel: string;
            /** Connector Source */
            connector_source: string;
            /** Next Poll At */
            next_poll_at?: string | null;
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /** GenericWebhookMapping */
        GenericWebhookMapping: {
            /** Actor Path */
            actor_path: string;
            /** Case Id Path */
            case_id_path?: string | null;
            /** Event Id Path */
            event_id_path?: string | null;
            /** Event Type Path */
            event_type_path: string;
            /** Occurred At Path */
            occurred_at_path: string;
            /** Payload Keys */
            payload_keys?: string[];
            /** Pii Redact Paths */
            pii_redact_paths?: string[];
        };
        /** GenericWebhookRegisterRequest */
        GenericWebhookRegisterRequest: {
            mapping: components["schemas"]["GenericWebhookMapping"];
            /**
             * Webhook Label
             * @description Tenant-friendly label, e.g. 'crm-events' or 'stripe-prod'
             */
            webhook_label: string;
        };
        /**
         * GmailOutlookRegisterRequest
         * @description POST body. enterprise_id is NEVER from here — K-12 header only.
         */
        GmailOutlookRegisterRequest: {
            /**
             * Channel
             * @description 'gmail' or 'outlook'
             */
            channel: string;
            /**
             * Oauth Credential Path
             * @description Vault path 'secret/tenant/{id}/connectors/gmail_oauth' in prod; env override in dev. Real adapters land P15-S11.
             */
            oauth_credential_path?: string | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
            /**
             * Tenant Mailbox
             * @description The mailbox to poll (also derives received vs sent direction)
             */
            tenant_mailbox: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MappingOverride */
        MappingOverride: {
            /** Canonical Name */
            canonical_name: string;
            /** Data Type */
            data_type: string;
            /** Source Column */
            source_column: string;
        };
        /** SchemaConfirmRequest */
        SchemaConfirmRequest: {
            /**
             * Overrides
             * @default []
             */
            overrides: components["schemas"]["MappingOverride"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** SchemaRequest */
        SchemaRequest: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** SharePointRegisterRequest */
        SharePointRegisterRequest: {
            /** Drive Id */
            drive_id: string;
            /** Oauth Credential Path */
            oauth_credential_path?: string | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
            /** Site Id */
            site_id: string;
        };
        /** SlackTeamsRegisterRequest */
        SlackTeamsRegisterRequest: {
            /**
             * Channel
             * @description 'slack' or 'teams'
             */
            channel: string;
            /** Oauth Credential Path */
            oauth_credential_path?: string | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
            /** Workspace Id */
            workspace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    trigger_analysis_analyze_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_cleaning_rules_clean_apply_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cleaning_suggestions_clean_suggestions_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanSuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bronze_files_data_bronze_files_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from prior meta.cursor */
                cursor?: string | null;
                limit?: number;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_bronze_file_data_bronze_files__file_id__sample_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path: {
                /** @description bronze_files.file_id */
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explorer_snapshot_data_explorer_get: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gold_customers_data_gold_customers_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from prior meta.cursor */
                cursor?: string | null;
                limit?: number;
                /** @description Filter to is_actioned=true|false; omit for all rows */
                actioned?: boolean | null;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_data_lineage_get: {
        parameters: {
            query: {
                /** @description bronze_files.file_id to trace */
                file_id: string;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_silver_datasets_data_silver_datasets_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from prior meta.cursor */
                cursor?: string | null;
                limit?: number;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_silver_dataset_data_silver_datasets__file_id__sample_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path: {
                /** @description silver dataset = silver_rows.file_id */
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_pipelines_pipelines_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from prior meta.cursor */
                cursor?: string | null;
                limit?: number;
                /** @description Comma-separated status filter */
                status?: string | null;
                /** @description ISO-8601 lower bound on created_at */
                from?: string | null;
                /** @description ISO-8601 upper bound on created_at */
                to?: string | null;
            };
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_stream_pipelines__run_id__events_get: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
                "Last-Event-ID"?: string | null;
            };
            path: {
                /** @description Pipeline run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_calendar_process_mining_connectors_calendar_post: {
        parameters: {
            query?: never;
            header: {
                "x-enterprise-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_generic_webhook_process_mining_connectors_generic_post: {
        parameters: {
            query?: never;
            header: {
                "x-enterprise-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenericWebhookRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_gmail_outlook_process_mining_connectors_gmail_outlook_post: {
        parameters: {
            query?: never;
            header: {
                "x-enterprise-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GmailOutlookRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_microsoft_sharepoint_process_mining_connectors_microsoft_post: {
        parameters: {
            query?: never;
            header: {
                "x-enterprise-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SharePointRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_slack_teams_process_mining_connectors_slack_teams_post: {
        parameters: {
            query?: never;
            header: {
                "x-enterprise-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlackTeamsRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_results__run_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path: {
                /** @description Pipeline run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_schema_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_schema_schema_confirm_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_canonical_fields_schema_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_file_upload_post: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
                "X-User-ID": string;
                "X-Department-ID"?: string | null;
                "X-Branch-ID"?: string | null;
                "X-Source-ID"?: string | null;
                "X-Workflow-Step-ID"?: string | null;
                "X-Requirement-ID"?: string | null;
                "X-Folder-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_status_upload__run_id__status_get: {
        parameters: {
            query?: never;
            header: {
                "X-Enterprise-ID": string;
            };
            path: {
                /** @description Pipeline run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
