-- =====================================================================
-- 069_production_templates_seed.sql
--
-- P2-S15 D2 — 25 production templates seed (5 per vertical × 5 verticals).
--
-- Marketing / Sales / Customer Service / Warehouse (ops) / Finance.
-- Each template uses node_type_catalog_key from mig 068.
-- industry_vertical column added for AI-HSC-016 cohort filter.
--
-- AUTO-GENERATED by scripts/generate_production_templates_p2_s15.py
-- Edit the script + re-run to regenerate. Both files committed.
-- =====================================================================

BEGIN;

-- Add industry_vertical column (idempotent ADD)
ALTER TABLE workflow_templates
    ADD COLUMN IF NOT EXISTS industry_vertical VARCHAR(32);

ALTER TABLE workflow_templates
    DROP CONSTRAINT IF EXISTS chk_industry_vertical;
ALTER TABLE workflow_templates
    ADD CONSTRAINT chk_industry_vertical CHECK (
        industry_vertical IS NULL OR industry_vertical IN (
            'general', 'retail', 'manufacturing', 'fintech',
            'logistics', 'healthcare', 'fmcg', 'saas'
        )
    );

CREATE INDEX IF NOT EXISTS idx_workflow_templates_industry
    ON workflow_templates(industry_vertical)
    WHERE is_active = TRUE;

-- Seed 25 production templates
INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Campaign Launch',
    'Khởi chạy chiến dịch marketing',
    'Define segment → A/B test content → manager approve → send → measure ROAS.',
    'marketing', 'campaign', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Define segment", "title_vi": "Xác định segment", "node_type_catalog_key": "read_table", "note": "Đọc customer table + filter theo segment criteria.", "hashtags": ["segmentation"], "required_document_types": [{"kind": "csv", "name": "Segment list", "required": true}], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Draft variants", "title_vi": "Soạn 2 variants", "node_type_catalog_key": "generate_narrative", "note": "Sinh 2 phiên bản subject + body cho A/B test.", "hashtags": ["content", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Manager approval", "title_vi": "Duyệt nội dung", "node_type_catalog_key": "approval_gate", "note": "Marketing manager duyệt cả 2 variants trước khi send.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send campaign", "title_vi": "Gửi chiến dịch", "node_type_catalog_key": "send_email", "note": "Send 50/50 split. idempotency_key = campaign_id+variant.", "hashtags": ["send", "ab_test"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Measure ROAS", "title_vi": "Đo ROAS", "node_type_catalog_key": "publish_insight", "note": "Tính revenue attribution / cost → ROAS. Publish vào Insight Hub.", "hashtags": ["roas", "kpi"], "required_document_types": [{"kind": "csv", "name": "Revenue attribution", "required": true}], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Churn Intervention',
    'Can thiệp khách rời',
    'Detect churn risk → classify reason → trigger save flow → measure save rate.',
    'marketing', 'retention', 'saas',
    '{"nodes": [{"client_id": "n1", "title": "Pull at-risk customers", "title_vi": "Lấy danh sách khách rủi ro", "node_type_catalog_key": "call_risk_detection", "note": "Risk detection trên 9 adoption signals — output high-risk list.", "hashtags": ["risk_detection", "churn"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Classify reason", "title_vi": "Phân loại nguyên nhân", "node_type_catalog_key": "classify_text", "note": "Phân loại từ feedback comments → pricing / feature / support / other.", "hashtags": ["classification"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Decide save offer", "title_vi": "Chọn save offer", "node_type_catalog_key": "if_else", "note": "Nếu reason=pricing thì discount offer; nếu feature thì 1-1 demo.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send save email", "title_vi": "Gửi email cứu", "node_type_catalog_key": "send_email", "note": "Personalized email + offer per reason cluster.", "hashtags": ["save", "personalize"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Track save rate", "title_vi": "Theo dõi save rate", "node_type_catalog_key": "publish_insight", "note": "30-day save rate per cohort. Promote winning variant.", "hashtags": ["retention", "kpi"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    12
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'VIP Onboarding',
    'Onboarding khách VIP',
    'VIP detection → CSM assignment → welcome call → activation milestone tracking.',
    'marketing', 'onboarding', 'fintech',
    '{"nodes": [{"client_id": "n1", "title": "Detect VIP signup", "title_vi": "Phát hiện khách VIP", "node_type_catalog_key": "read_webhook", "note": "Webhook từ payment system khi LTV > 50M VND ngay từ first transaction.", "hashtags": ["vip", "intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Create CSM task", "title_vi": "Tạo task cho CSM", "node_type_catalog_key": "create_task", "note": "Assign tới CSM team với SLA 24h.", "hashtags": ["csm", "assignment"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Schedule welcome call", "title_vi": "Lên lịch welcome call", "node_type_catalog_key": "send_email", "note": "Gửi link Calendly để khách book 30-min call.", "hashtags": ["calendar"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Track activation", "title_vi": "Theo dõi activation", "node_type_catalog_key": "rag_query", "note": "RAG query xem khách đã đạt 3/5 activation milestones chưa.", "hashtags": ["activation"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Update VIP dashboard", "title_vi": "Cập nhật dashboard VIP", "node_type_catalog_key": "display_dashboard", "note": "Realtime VIP funnel tile cho Sales Director.", "hashtags": ["dashboard"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    15
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Lead Nurture Sequence',
    'Chuỗi nuôi dưỡng lead',
    'Lead intake → score → drip email sequence → handoff to sales when MQL.',
    'marketing', 'lead_gen', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Lead intake", "title_vi": "Tiếp nhận lead", "node_type_catalog_key": "read_form_submission", "note": "Webhook từ marketing form / Zalo OA / Facebook lead form.", "hashtags": ["intake", "lead"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Score lead", "title_vi": "Chấm điểm lead", "node_type_catalog_key": "call_insight_engine", "note": "AI score 0-100 dựa trên company size / industry / engagement.", "hashtags": ["scoring", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Branch by score", "title_vi": "Phân nhánh theo điểm", "node_type_catalog_key": "switch", "note": "0-30 = cold drip, 31-70 = warm drip, 71+ = MQL handoff.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Drip email", "title_vi": "Gửi drip email", "node_type_catalog_key": "send_email", "note": "Email sequence theo cluster. idempotency_key = lead_id+step.", "hashtags": ["drip", "nurture"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Handoff to sales", "title_vi": "Chuyển sang sales", "node_type_catalog_key": "trigger_workflow", "note": "Trigger ''Lead Qualification'' workflow khi đạt MQL.", "hashtags": ["handoff"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    8
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Email A/B Test',
    'A/B test email',
    'Create variants → split audience → send → measure → declare winner.',
    'marketing', 'experiment', 'retail',
    '{"nodes": [{"client_id": "n1", "title": "Define hypothesis", "title_vi": "Định nghĩa giả thuyết", "node_type_catalog_key": "read_form_submission", "note": "Form nhập hypothesis + success metric (CTR / conversion / revenue).", "hashtags": ["experiment"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Generate variants", "title_vi": "Sinh variants", "node_type_catalog_key": "generate_narrative", "note": "Sinh A vs B (subject line / CTA / hero copy).", "hashtags": ["content"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Split audience", "title_vi": "Tách audience 50/50", "node_type_catalog_key": "split", "note": "Random split với seed cố định cho reproducibility.", "hashtags": ["split"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send both variants", "title_vi": "Gửi cả 2", "node_type_catalog_key": "send_email", "note": "Gửi A tới half, B tới half. Idempotency_key per variant.", "hashtags": ["send"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Declare winner", "title_vi": "Công bố winner", "node_type_catalog_key": "publish_insight", "note": "Statistical test (p<0.05) + auto-promote winning variant cho lần sau.", "hashtags": ["winner", "kpi"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    6
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Lead Qualification',
    'Đánh giá lead',
    'BANT scoring → routing to AE → first-touch follow-up.',
    'sales', 'qualification', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Read lead pool", "title_vi": "Đọc lead pool", "node_type_catalog_key": "read_table", "note": "SELECT từ leads WHERE status=''new'' AND created_at > now()-interval ''24h''.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "BANT score", "title_vi": "Chấm BANT", "node_type_catalog_key": "call_insight_engine", "note": "AI evaluate Budget/Authority/Need/Timeline → score 0-100.", "hashtags": ["bant", "scoring"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Route by score", "title_vi": "Phân tuyến", "node_type_catalog_key": "switch", "note": "70+ = senior AE, 40-70 = mid AE, <40 = nurture pool.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Create AE task", "title_vi": "Tạo task AE", "node_type_catalog_key": "create_task", "note": "Task với SLA 4h cho senior AE, 24h cho mid AE.", "hashtags": ["assignment"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Send first-touch", "title_vi": "Gửi first-touch", "node_type_catalog_key": "send_email", "note": "Personalized intro email từ AE.", "hashtags": ["first_touch"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    8
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Proposal Approval',
    'Duyệt proposal',
    'Draft → margin check → manager approval → send to customer → track signature.',
    'sales', 'approval', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Read deal data", "title_vi": "Đọc dữ liệu deal", "node_type_catalog_key": "read_table", "note": "Pull deal + customer info từ CRM.", "hashtags": ["intake"], "required_document_types": [{"kind": "csv", "name": "Deal data export", "required": true}], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Calculate margin", "title_vi": "Tính margin", "node_type_catalog_key": "aggregate", "note": "Tính gross_margin = (price - cogs) / price. NUMERIC(5,4).", "hashtags": ["margin", "kpi"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Manager approval", "title_vi": "Duyệt manager", "node_type_catalog_key": "approval_gate", "note": "Margin >= 25%: auto-approve. <25%: cần sales manager duyệt.", "hashtags": ["approval", "gate"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send proposal", "title_vi": "Gửi proposal", "node_type_catalog_key": "send_email", "note": "Gửi PDF proposal + signing link (DocuSign).", "hashtags": ["send", "proposal"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Track signature", "title_vi": "Theo dõi ký", "node_type_catalog_key": "publish_alert", "note": "Alert khi >48h chưa ký → AE follow up.", "hashtags": ["sla", "tracking"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Contract Renewal',
    'Gia hạn hợp đồng',
    '90-day pre-expiry trigger → health check → renewal proposal → close.',
    'sales', 'renewal', 'saas',
    '{"nodes": [{"client_id": "n1", "title": "Detect expiry", "title_vi": "Phát hiện sắp hết hạn", "node_type_catalog_key": "scheduled_trigger", "note": "Cron daily 9am: WHERE end_date BETWEEN now()+60d AND now()+90d.", "hashtags": ["expiry", "schedule"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Account health check", "title_vi": "Health check", "node_type_catalog_key": "call_risk_detection", "note": "Risk detection trên 9 adoption signals → green/yellow/red.", "hashtags": ["health", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Choose play", "title_vi": "Chọn renewal play", "node_type_catalog_key": "if_else", "note": "Green = auto-renewal email. Yellow = save-flow. Red = exec-led save.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send renewal proposal", "title_vi": "Gửi proposal renewal", "node_type_catalog_key": "send_email", "note": "Tailored per health tier (renewal price / upsell / save offer).", "hashtags": ["proposal"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Track close", "title_vi": "Theo dõi đóng deal", "node_type_catalog_key": "create_task", "note": "Task AE follow up 7 ngày sau gửi proposal.", "hashtags": ["follow_up"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    12
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Discount Approval',
    'Duyệt giảm giá',
    'Discount request → tiered approval (depth → role) → notify customer.',
    'sales', 'approval', 'retail',
    '{"nodes": [{"client_id": "n1", "title": "Receive request", "title_vi": "Nhận yêu cầu", "node_type_catalog_key": "read_form_submission", "note": "Form từ AE với customer + product + discount_pct + reason.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Validate ceiling", "title_vi": "Kiểm tra trần", "node_type_catalog_key": "validate", "note": "Schema validate + business rule: discount_pct must be 0-50.", "hashtags": ["validation"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Route by depth", "title_vi": "Phân tuyến theo độ sâu", "node_type_catalog_key": "switch", "note": "<10% AE tự duyệt. 10-25% manager. >25% director.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Manager approval", "title_vi": "Duyệt", "node_type_catalog_key": "approval_gate", "note": "Approver_role theo switch. SLA 4h. Timeout = reject.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Notify customer", "title_vi": "Báo khách", "node_type_catalog_key": "send_email", "note": "Email approved discount + new pricing.", "hashtags": ["notify"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    6
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Pipeline Review',
    'Review pipeline',
    'Weekly pipeline aggregation → forecast → manager review → action items.',
    'sales', 'reporting', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Pull pipeline", "title_vi": "Lấy pipeline", "node_type_catalog_key": "read_table", "note": "SELECT từ deals WHERE stage NOT IN (''won'',''lost'').", "hashtags": ["pipeline"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Aggregate by stage", "title_vi": "Group by stage", "node_type_catalog_key": "aggregate", "note": "Group by stage + count + sum(amount). NUMERIC(14,4) money.", "hashtags": ["aggregation"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Forecast close", "title_vi": "Dự báo close", "node_type_catalog_key": "call_forecasting", "note": "Forecast 30-day close revenue (Prophet method).", "hashtags": ["forecast", "ai"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Generate narrative", "title_vi": "Sinh narrative", "node_type_catalog_key": "generate_narrative", "note": "Executive-style summary cho Sales Director Monday meeting.", "hashtags": ["narrative", "ai"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Publish to dashboard", "title_vi": "Publish dashboard", "node_type_catalog_key": "display_dashboard", "note": "Render Pipeline tile vào Sales Director dashboard.", "hashtags": ["dashboard"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    5
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Ticket Triage',
    'Phân loại ticket',
    'Inbound ticket → AI classify → priority routing → SLA timer.',
    'customer_service', 'triage', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Read inbound ticket", "title_vi": "Đọc ticket vào", "node_type_catalog_key": "read_email", "note": "Đọc email support@... + Zalo chat. Stage 2 mapping.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Classify category", "title_vi": "Phân loại category", "node_type_catalog_key": "classify_text", "note": "Multi-label: billing / technical / sales / refund / other.", "hashtags": ["classification", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Set priority", "title_vi": "Đặt priority", "node_type_catalog_key": "switch", "note": "Critical = VIP customer + outage word. High = refund. Mid = default.", "hashtags": ["priority"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Create ticket", "title_vi": "Tạo ticket", "node_type_catalog_key": "create_task", "note": "Tạo task trong queue, assign tier-1 agent.", "hashtags": ["assignment"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Start SLA timer", "title_vi": "Bắt đầu SLA", "node_type_catalog_key": "publish_alert", "note": "Alert nếu Critical >1h, High >4h, Mid >24h chưa first response.", "hashtags": ["sla"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    8
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'SLA Escalation',
    'Escalate khi quá SLA',
    'Monitor SLA → escalate to tier-2 → notify manager → re-assign.',
    'customer_service', 'escalation', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Check SLA breach", "title_vi": "Check vi phạm SLA", "node_type_catalog_key": "scheduled_trigger", "note": "Mỗi 15 phút: WHERE first_response_at IS NULL AND created_at + sla_window < now().", "hashtags": ["sla", "schedule"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Filter breaches", "title_vi": "Lọc vi phạm", "node_type_catalog_key": "filter", "note": "Pure filter trên tickets đã breach.", "hashtags": ["filter"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Notify tier-2", "title_vi": "Thông báo tier-2", "node_type_catalog_key": "send_chat_message", "note": "Slack/Telegram notification cho tier-2 + manager.", "hashtags": ["notify", "escalation"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Re-assign", "title_vi": "Re-assign", "node_type_catalog_key": "update_record", "note": "UPDATE ticket SET assigned_to = tier_2_pool, escalated_at = now().", "hashtags": ["assignment"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Log incident", "title_vi": "Log sự cố", "node_type_catalog_key": "log", "note": "Structured log cho post-mortem analysis.", "hashtags": ["audit"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    5
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'NPS Follow-up',
    'Follow-up NPS',
    'NPS survey response → categorize → promoter outreach / detractor save.',
    'customer_service', 'feedback', 'saas',
    '{"nodes": [{"client_id": "n1", "title": "Read NPS response", "title_vi": "Đọc phản hồi NPS", "node_type_catalog_key": "read_form_submission", "note": "Webhook khi customer trả lời survey (score 0-10).", "hashtags": ["nps", "intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Categorize", "title_vi": "Phân loại", "node_type_catalog_key": "if_else", "note": "Score 9-10 = promoter. 7-8 = passive. 0-6 = detractor.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Extract reason", "title_vi": "Trích lý do", "node_type_catalog_key": "extract_entities", "note": "NER trên comment để hiểu specific reason.", "hashtags": ["nlp", "ai"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send response", "title_vi": "Gửi phản hồi", "node_type_catalog_key": "send_email", "note": "Promoter = thank-you + referral ask. Detractor = CSM call schedule.", "hashtags": ["follow_up"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Update CRM record", "title_vi": "Cập nhật CRM", "node_type_catalog_key": "update_record", "note": "UPDATE customers SET last_nps = score, nps_updated_at = now().", "hashtags": ["crm"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    7
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Refund Approval',
    'Duyệt hoàn tiền',
    'Refund request → policy check → manager approval (if needed) → process.',
    'customer_service', 'approval', 'retail',
    '{"nodes": [{"client_id": "n1", "title": "Read refund request", "title_vi": "Đọc yêu cầu hoàn tiền", "node_type_catalog_key": "read_form_submission", "note": "Form với order_id + reason + amount.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Validate policy", "title_vi": "Kiểm policy", "node_type_catalog_key": "validate", "note": "Check policy: <30 days + valid reason category.", "hashtags": ["policy"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Check threshold", "title_vi": "Kiểm threshold", "node_type_catalog_key": "if_else", "note": "Amount < 500K VND auto-approve. >= 500K cần manager.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Manager approval", "title_vi": "Duyệt manager", "node_type_catalog_key": "approval_gate", "note": "CS manager duyệt với SLA 24h. Timeout = escalate.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Process refund", "title_vi": "Xử lý hoàn tiền", "node_type_catalog_key": "call_api", "note": "POST /payment/refund với idempotency_key. Saga compensation = stop_refund.", "hashtags": ["payment"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    6
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Churn Save',
    'Cứu khách rời',
    'Cancellation request → reason capture → save offer → exec escalation if VIP.',
    'customer_service', 'retention', 'saas',
    '{"nodes": [{"client_id": "n1", "title": "Receive cancellation", "title_vi": "Nhận yêu cầu hủy", "node_type_catalog_key": "read_form_submission", "note": "Cancel form từ Portal Settings.", "hashtags": ["churn", "intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Classify reason", "title_vi": "Phân loại lý do", "node_type_catalog_key": "classify_text", "note": "Reason cluster: pricing / feature / support / business_change.", "hashtags": ["classification", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Check VIP", "title_vi": "Check VIP", "node_type_catalog_key": "if_else", "note": "LTV > 100M VND → exec-led save. Else → standard save.", "hashtags": ["routing"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Send save offer", "title_vi": "Gửi save offer", "node_type_catalog_key": "send_email", "note": "Offer per cluster. VIP gets exec-personalized email.", "hashtags": ["save"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Track save outcome", "title_vi": "Theo dõi kết quả", "node_type_catalog_key": "publish_insight", "note": "30-day save rate per cluster. Publish Insight Hub.", "hashtags": ["kpi"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Inventory Restock',
    'Nhập kho khi sắp hết',
    'Daily stock check → low-stock detection → auto-PO → vendor notification.',
    'warehouse', 'restock', 'retail',
    '{"nodes": [{"client_id": "n1", "title": "Read inventory", "title_vi": "Đọc tồn kho", "node_type_catalog_key": "read_table", "note": "SELECT từ inventory WHERE stock < reorder_threshold.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Aggregate by SKU", "title_vi": "Gộp theo SKU", "node_type_catalog_key": "aggregate", "note": "Group by sku + sum(stock) per warehouse.", "hashtags": ["aggregation"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Generate PO draft", "title_vi": "Sinh PO draft", "node_type_catalog_key": "generate_narrative", "note": "Sinh PO text + quantity tự động.", "hashtags": ["ai"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Manager approval", "title_vi": "Duyệt PO", "node_type_catalog_key": "approval_gate", "note": "Warehouse manager duyệt nếu total PO > 50M VND.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Send PO to vendor", "title_vi": "Gửi PO vendor", "node_type_catalog_key": "send_email", "note": "Email PO PDF tới supplier. idempotency_key = po_number.", "hashtags": ["procurement"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Supplier Audit',
    'Audit supplier định kỳ',
    'Quarterly schedule → pull supplier performance → score → flag underperformers.',
    'warehouse', 'audit', 'manufacturing',
    '{"nodes": [{"client_id": "n1", "title": "Quarterly trigger", "title_vi": "Trigger hàng quý", "node_type_catalog_key": "scheduled_trigger", "note": "Cron Q1/Q2/Q3/Q4 first business day.", "hashtags": ["audit", "schedule"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Pull supplier metrics", "title_vi": "Lấy metric supplier", "node_type_catalog_key": "read_table", "note": "SELECT từ supplier_metrics: on_time_rate, defect_rate, response_time.", "hashtags": ["supplier"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Score supplier", "title_vi": "Chấm điểm", "node_type_catalog_key": "call_insight_engine", "note": "AI scoring 0-100 per supplier.", "hashtags": ["scoring", "ai"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Flag underperformers", "title_vi": "Đánh dấu yếu", "node_type_catalog_key": "filter", "note": "Filter score < 60 → review queue.", "hashtags": ["audit"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Notify procurement", "title_vi": "Báo procurement", "node_type_catalog_key": "send_chat_message", "note": "Slack tới procurement team với underperformer list.", "hashtags": ["notify"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    8
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Quality Check',
    'QC nhận hàng',
    'Goods receipt → sample inspection → defect rate → accept / reject / partial.',
    'warehouse', 'quality', 'manufacturing',
    '{"nodes": [{"client_id": "n1", "title": "Receive goods", "title_vi": "Nhận hàng", "node_type_catalog_key": "read_form_submission", "note": "Form QC nhập sample size + defects found.", "hashtags": ["qc", "intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Calculate defect rate", "title_vi": "Tính defect rate", "node_type_catalog_key": "transform", "note": "rate = defects / sample. NUMERIC(5,4).", "hashtags": ["calc"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Decide action", "title_vi": "Quyết định", "node_type_catalog_key": "switch", "note": "Rate <1% accept. 1-5% partial. >5% reject.", "hashtags": ["decision"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Update inventory", "title_vi": "Cập nhật tồn kho", "node_type_catalog_key": "save_to_database", "note": "INSERT into inventory với status accepted/quarantined.", "hashtags": ["inventory"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Notify supplier", "title_vi": "Báo supplier", "node_type_catalog_key": "send_email", "note": "Email kết quả QC. Reject = return + claim.", "hashtags": ["supplier"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    7
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Shipment Dispatch',
    'Điều phối giao hàng',
    'Order ready → carrier selection → label generation → handoff → track.',
    'warehouse', 'logistics', 'logistics',
    '{"nodes": [{"client_id": "n1", "title": "Read ready orders", "title_vi": "Đọc order sẵn", "node_type_catalog_key": "read_table", "note": "SELECT WHERE pack_status=''ready'' AND ship_date <= today.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Choose carrier", "title_vi": "Chọn carrier", "node_type_catalog_key": "call_recommendation_engine", "note": "AI gợi ý carrier dựa trên zone + size + cost + SLA.", "hashtags": ["routing", "ai"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Generate label", "title_vi": "Tạo label", "node_type_catalog_key": "call_api", "note": "POST /carrier/label với idempotency_key = order_id.", "hashtags": ["label"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Update order status", "title_vi": "Cập nhật status", "node_type_catalog_key": "update_record", "note": "UPDATE orders SET status=''shipped'', tracking_no = ...", "hashtags": ["status"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Notify customer", "title_vi": "Báo khách", "node_type_catalog_key": "send_email", "note": "Email tracking link cho khách.", "hashtags": ["notify"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    8
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Warranty Claim',
    'Xử lý bảo hành',
    'Claim intake → validate → assign technician → process → close.',
    'warehouse', 'warranty', 'retail',
    '{"nodes": [{"client_id": "n1", "title": "Receive claim", "title_vi": "Nhận claim", "node_type_catalog_key": "read_form_submission", "note": "Form claim với serial + issue + photos.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Validate warranty", "title_vi": "Kiểm bảo hành", "node_type_catalog_key": "validate", "note": "Schema validate + check purchase_date + warranty_period.", "hashtags": ["validation"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Assign technician", "title_vi": "Phân kỹ thuật viên", "node_type_catalog_key": "create_task", "note": "Task tới technician pool. SLA 48h.", "hashtags": ["assignment"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Track resolution", "title_vi": "Theo dõi xử lý", "node_type_catalog_key": "publish_alert", "note": "Alert manager nếu >SLA chưa resolve.", "hashtags": ["sla"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Close claim", "title_vi": "Đóng claim", "node_type_catalog_key": "send_email", "note": "Email khách với resolution + survey link.", "hashtags": ["close"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    9
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Invoice Approval',
    'Duyệt hóa đơn',
    'Invoice intake → 3-way match → tiered approval → payment scheduling.',
    'finance', 'approval', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Read incoming invoice", "title_vi": "Đọc hóa đơn vào", "node_type_catalog_key": "read_email", "note": "Đọc hóa đơn từ AP mailbox + PDF extraction (Stage 6).", "hashtags": ["intake", "ap"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "3-way match", "title_vi": "3-way match", "node_type_catalog_key": "join", "note": "Join invoice + PO + GR (goods receipt) theo PO number.", "hashtags": ["match"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Validate amounts", "title_vi": "Kiểm số tiền", "node_type_catalog_key": "validate", "note": "Validate invoice_amount = po_amount ± 5% tolerance.", "hashtags": ["validation"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Tiered approval", "title_vi": "Duyệt theo tier", "node_type_catalog_key": "approval_gate", "note": "<10M tự duyệt. 10-100M finance manager. >100M CFO.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Schedule payment", "title_vi": "Lên lịch thanh toán", "node_type_catalog_key": "create_task", "note": "Tạo payment task với due_date = invoice_date + net_terms.", "hashtags": ["payment"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Expense Reimbursement',
    'Hoàn ứng chi phí',
    'Submit expense → policy check → manager approval → reimburse.',
    'finance', 'approval', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Submit expense", "title_vi": "Nộp expense", "node_type_catalog_key": "read_form_submission", "note": "Form expense với category + amount + receipt attachment.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Policy check", "title_vi": "Kiểm policy", "node_type_catalog_key": "validate", "note": "Per-category caps + receipt required validation.", "hashtags": ["policy"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Classify category", "title_vi": "Phân loại", "node_type_catalog_key": "classify_text", "note": "AI classify khi user nhập tự do (travel/meal/supplies/other).", "hashtags": ["ai"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Manager approval", "title_vi": "Duyệt manager", "node_type_catalog_key": "approval_gate", "note": "Auto <500K. Manager 500K-5M. Director >5M.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Reimburse", "title_vi": "Chuyển tiền", "node_type_catalog_key": "call_api", "note": "POST /payroll/reimburse. idempotency_key = expense_id.", "hashtags": ["payment"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    6
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Monthly Close',
    'Đóng sổ tháng',
    'Trigger month-end → aggregate ledger → reconcile → publish report.',
    'finance', 'reporting', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Month-end trigger", "title_vi": "Trigger cuối tháng", "node_type_catalog_key": "scheduled_trigger", "note": "Cron last business day of month at 18:00 ICT.", "hashtags": ["schedule"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Aggregate GL", "title_vi": "Gộp GL", "node_type_catalog_key": "aggregate", "note": "Sum theo account + cost_center + month. NUMERIC(14,4).", "hashtags": ["accounting"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Reconcile bank", "title_vi": "Đối chiếu ngân hàng", "node_type_catalog_key": "join", "note": "Join GL với bank_statements. Flag mismatches.", "hashtags": ["reconcile"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Generate close report", "title_vi": "Sinh báo cáo close", "node_type_catalog_key": "generate_report", "note": "PDF với P&L + Balance Sheet + Cash Flow.", "hashtags": ["report"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Publish to CFO", "title_vi": "Publish CFO", "node_type_catalog_key": "send_email", "note": "Email CFO + Board với report attached.", "hashtags": ["publish"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    15
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Vendor Payment',
    'Thanh toán nhà cung cấp',
    'Payment due → batch invoices → CFO approval → process → reconcile.',
    'finance', 'payment', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Pull due payments", "title_vi": "Lấy payment đến hạn", "node_type_catalog_key": "read_table", "note": "WHERE due_date BETWEEN today AND today+7d AND status=''approved''.", "hashtags": ["intake"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Batch by vendor", "title_vi": "Gộp theo vendor", "node_type_catalog_key": "aggregate", "note": "Group by vendor + sum(amount) → single batch payment per vendor.", "hashtags": ["batch"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "CFO batch approval", "title_vi": "Duyệt CFO batch", "node_type_catalog_key": "approval_gate", "note": "Single approval cho cả batch để giảm friction.", "hashtags": ["approval"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Process payments", "title_vi": "Xử lý payment", "node_type_catalog_key": "call_api", "note": "POST /bank/payment-batch. Saga compensation = void_batch.", "hashtags": ["payment"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Update AP ledger", "title_vi": "Cập nhật sổ AP", "node_type_catalog_key": "save_to_database", "note": "INSERT vào ap_payments + UPDATE invoices SET paid_at = now().", "hashtags": ["ledger"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    10
);

INSERT INTO workflow_templates (
    display_name, display_name_vi, description,
    department_type, category, industry_vertical,
    workflow_definition, estimated_setup_minutes
) VALUES (
    'Budget Approval',
    'Duyệt ngân sách',
    'Annual budget submission → finance review → board approval → publish.',
    'finance', 'approval', 'general',
    '{"nodes": [{"client_id": "n1", "title": "Submit budget", "title_vi": "Nộp ngân sách", "node_type_catalog_key": "read_form_submission", "note": "Form từ department heads với line items + justification.", "hashtags": ["intake", "annual"], "required_document_types": [], "sequence_order": 1, "position_x": 100, "position_y": 100}, {"client_id": "n2", "title": "Validate format", "title_vi": "Kiểm format", "node_type_catalog_key": "validate", "note": "Schema validate + sum check + variance vs prior year.", "hashtags": ["validation"], "required_document_types": [], "sequence_order": 2, "position_x": 320, "position_y": 100}, {"client_id": "n3", "title": "Finance review", "title_vi": "Review finance", "node_type_catalog_key": "approval_gate", "note": "Finance Director review + comments.", "hashtags": ["review"], "required_document_types": [], "sequence_order": 3, "position_x": 540, "position_y": 100}, {"client_id": "n4", "title": "Board approval", "title_vi": "Duyệt board", "node_type_catalog_key": "approval_gate", "note": "Board vote (anh + co-founders) với SLA 14 ngày.", "hashtags": ["approval", "board"], "required_document_types": [], "sequence_order": 4, "position_x": 760, "position_y": 100}, {"client_id": "n5", "title": "Publish approved budget", "title_vi": "Publish budget", "node_type_catalog_key": "publish_insight", "note": "Publish vào Insight Hub. Department heads notified.", "hashtags": ["publish"], "required_document_types": [], "sequence_order": 5, "position_x": 980, "position_y": 100}], "edges": [{"source_client_id": "n1", "target_client_id": "n2", "label": "next"}, {"source_client_id": "n2", "target_client_id": "n3", "label": "next"}, {"source_client_id": "n3", "target_client_id": "n4", "label": "next"}, {"source_client_id": "n4", "target_client_id": "n5", "label": "next"}]}'::jsonb,
    12
);

COMMIT;
