bind 0.0.0.0
protected-mode no
port 6379

# Memory management
maxmemory 512mb
maxmemory-policy allkeys-lru

# Persistence
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# Key expiry
hz 20

# Logging
loglevel notice
