package com.kaorisystem.auth.it;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MvcResult;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * End-to-end flow for the F-009 nested key endpoints against real Postgres.
 *
 * Covers: create-workspace → list-keys → generate → list-with-1-key →
 * revoke → revoke-again-404, plus cross-workspace IDOR rejection and the
 * audit-log side effect.
 *
 * Redis is mocked at the AbstractIntegrationIT level; PlatformKeyService's
 * rate-limit branch is therefore inert (Long count is null), so generation
 * never trips the 20/hour limit during IT runs.
 */
@DisplayName("E2E — Workspace API key CRUD + IDOR + audit side-effect")
class WorkspaceKeyFlowIT extends AbstractIntegrationIT {

    private String createWorkspace() throws Exception {
        String body = """
                {"name":"%s","plan_code":"TRIAL","industry":"Bán lẻ"}
                """.formatted("IT-Keys-" + UUID.randomUUID());
        MvcResult res = mockMvc.perform(post("/api/v1/platform/workspaces")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isCreated())
                .andReturn();
        return objectMapper.readTree(res.getResponse().getContentAsString())
                .get("data").get("workspace_id").asText();
    }

    private String generateKey(String workspaceId, String label) throws Exception {
        MvcResult res = mockMvc.perform(post("/api/v1/platform/workspaces/" + workspaceId + "/keys")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"label":"%s"}
                                """.formatted(label)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.raw_key").exists())
                .andExpect(jsonPath("$.data.label").value(label))
                .andExpect(jsonPath("$.data.status").value("active"))
                .andExpect(jsonPath("$.meta.warning").exists())
                .andReturn();
        JsonNode envelope = objectMapper.readTree(res.getResponse().getContentAsString());
        // Sanity-check the key format generated by PlatformKeyService.
        String raw = envelope.get("data").get("raw_key").asText();
        assertThat(raw).startsWith("KAORI-").matches("KAORI(-[A-Z0-9]{8}){4}");
        return envelope.get("data").get("key_id").asText();
    }

    @Test
    @DisplayName("create → list → revoke: full key lifecycle for a workspace")
    void key_fullLifecycle() throws Exception {
        String workspaceId = createWorkspace();

        // 1. list — empty initially
        mockMvc.perform(get("/api/v1/platform/workspaces/" + workspaceId + "/keys"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.length()").value(0));

        // 2. generate two keys
        String keyA = generateKey(workspaceId, "ci-runner");
        String keyB = generateKey(workspaceId, "stg-deploy");

        // 3. list — both shown, no raw_key, ordered newest first
        MvcResult listed = mockMvc.perform(get("/api/v1/platform/workspaces/" + workspaceId + "/keys"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.length()").value(2))
                .andExpect(jsonPath("$.data[0].raw_key").doesNotExist())
                .andExpect(jsonPath("$.data[0].key_hash").doesNotExist())
                .andReturn();
        JsonNode items = objectMapper.readTree(listed.getResponse().getContentAsString())
                .get("data");
        for (JsonNode it : items) {
            assertThat(it.get("status").asText()).isEqualTo("active");
        }

        // 4. revoke A
        mockMvc.perform(delete("/api/v1/platform/workspaces/" + workspaceId + "/keys/" + keyA))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.key_id").value(keyA))
                .andExpect(jsonPath("$.data.status").value("revoked"));

        // 5. revoke A again → 404
        mockMvc.perform(delete("/api/v1/platform/workspaces/" + workspaceId + "/keys/" + keyA))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.title").value("Key not found"));

        // 6. list now shows A as revoked, B still active
        MvcResult after = mockMvc.perform(get("/api/v1/platform/workspaces/" + workspaceId + "/keys"))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode rows = objectMapper.readTree(after.getResponse().getContentAsString())
                .get("data");
        for (JsonNode it : rows) {
            String kid = it.get("key_id").asText();
            String stt = it.get("status").asText();
            if (kid.equals(keyA)) assertThat(stt).isEqualTo("revoked");
            if (kid.equals(keyB)) assertThat(stt).isEqualTo("active");
        }
    }

    @Test
    @DisplayName("IDOR: revoking a key that belongs to a different workspace returns 404")
    void revoke_crossWorkspace() throws Exception {
        String wsA = createWorkspace();
        String wsB = createWorkspace();
        String keyInB = generateKey(wsB, "in-B");

        // Try to revoke key-in-B via workspace-A's path.
        mockMvc.perform(delete("/api/v1/platform/workspaces/" + wsA + "/keys/" + keyInB))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.title").value("Key not found"));

        // Confirm key-in-B is still active under its real workspace.
        MvcResult bList = mockMvc.perform(get("/api/v1/platform/workspaces/" + wsB + "/keys"))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode bItems = objectMapper.readTree(bList.getResponse().getContentAsString())
                .get("data");
        boolean stillActive = false;
        for (JsonNode it : bItems) {
            if (it.get("key_id").asText().equals(keyInB)) {
                stillActive = "active".equals(it.get("status").asText());
            }
        }
        assertThat(stillActive).isTrue();
    }

    @Test
    @DisplayName("Audit log captures key.generated + key.revoked events")
    void audit_keyEvents() throws Exception {
        String workspaceId = createWorkspace();
        String keyId = generateKey(workspaceId, "audit-target");
        mockMvc.perform(delete("/api/v1/platform/workspaces/" + workspaceId + "/keys/" + keyId))
                .andExpect(status().isOk());

        MvcResult auditRes = mockMvc.perform(get("/api/v1/platform/workspaces/" + workspaceId + "/audit"))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode events = objectMapper.readTree(auditRes.getResponse().getContentAsString())
                .get("data");

        boolean sawGenerated = false;
        boolean sawRevoked   = false;
        for (JsonNode ev : events) {
            String type = ev.get("event_type").asText();
            if ("key.generated".equals(type)) sawGenerated = true;
            if ("key.revoked".equals(type))   sawRevoked   = true;
        }
        assertThat(sawGenerated).as("key.generated audit row missing").isTrue();
        assertThat(sawRevoked).as("key.revoked audit row missing").isTrue();
    }

    @Test
    @DisplayName("GET on unknown workspace returns 404, not empty list")
    void list_unknownWorkspace() throws Exception {
        UUID phantom = UUID.randomUUID();
        mockMvc.perform(get("/api/v1/platform/workspaces/" + phantom + "/keys"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.title").value("Workspace not found"));
    }
}
