#!/usr/bin/env python3
"""
Phase 2 error-handling B3 PR #9 — schema drift detector (#13 migration safety).

Computes a deterministic fingerprint of the live PostgreSQL schema (tables,
columns, indexes, constraints, RLS policies, sequences) and either:

  * ``--write`` — writes the fingerprint to ``infrastructure/postgres/
                  schema_snapshot.txt`` (commit alongside any migration).
  * ``--check`` — computes the fingerprint and diffs against the committed
                  snapshot. Exits ``1`` on drift, prints a unified diff.

Why a structured fingerprint, not pg_dump
-----------------------------------------
``pg_dump --schema-only`` is volatile across Postgres versions: trigger
ordering, comment placement, and ``ALTER ... OWNER`` lines move around
between minor releases. Our fingerprint reads ``information_schema`` +
``pg_catalog`` and renders a sorted, plain-text representation that's
stable across Postgres 15.x patch releases and reproducible regardless
of the order migrations were applied (the schema is the same; the
fingerprint is the same).

Dev workflow
------------
After adding migration ``NNN_*.sql``::

    docker compose up postgres -d
    psql -U kaori -d kaori -f infrastructure/postgres/migrations/NNN_*.sql
    python scripts/schema-drift.py --write \\
        --url postgresql://kaori:kaori_dev_password@localhost:5432/kaori
    git add infrastructure/postgres/schema_snapshot.txt

CI runs the fresh-DB version (apply every migration to an empty
Postgres, then ``--check`` against the committed snapshot). If a
migration is added or modified without updating the snapshot, CI fails.

Usage
-----
::

    # Write / refresh the committed snapshot.
    python scripts/schema-drift.py --write [--url <PG_URL>] [--snapshot <PATH>]

    # Verify the live DB matches the committed snapshot (CI mode).
    python scripts/schema-drift.py --check [--url <PG_URL>] [--snapshot <PATH>]

Exit codes: ``0`` = OK, ``1`` = drift detected (or CLI error), ``2`` = unable to connect.
"""

from __future__ import annotations

import argparse
import difflib
import io
import os
import sys
from pathlib import Path

if hasattr(sys.stdout, "buffer"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", line_buffering=True)
if hasattr(sys.stderr, "buffer"):
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", line_buffering=True)

DEFAULT_SNAPSHOT_PATH = Path(__file__).resolve().parent.parent / "infrastructure" / "postgres" / "schema_snapshot.txt"
DEFAULT_PG_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://kaori:kaori_dev_password@localhost:5432/kaori",
)

# Tables that are managed by Flyway itself — exclude so the fingerprint
# doesn't churn on every schema_history insert when CI applies a new
# migration during the run.
EXCLUDED_TABLES = {"flyway_schema_history"}

# Partition CHILD tables (relispartition = true) are auto-provisioned by
# date-rolling routines — e.g. guardrail_violations_2026_06,
# api_request_log_2026_06. Their names and presence depend on the wall
# clock at apply time, so including them makes the fingerprint
# non-deterministic across calendar months: the snapshot would drift every
# time the partition window rolls forward, even with zero schema changes
# (this is exactly what reddened migration-test on main). We exclude the
# children and keep the PARTITIONED parent (relkind 'p'), whose columns and
# constraints fully define each partition's structure. The child set is
# resolved at runtime from pg_class — never hard-coded.
Q_PARTITION_CHILDREN = """
SELECT c.relname
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
 WHERE n.nspname = 'public'
   AND c.relispartition
"""

# Header inserted at the top of the snapshot file. Helps a human reader
# understand what they're looking at when grepping git history.
SNAPSHOT_HEADER = (
    "# Auto-generated by scripts/schema-drift.py — DO NOT EDIT BY HAND.\n"
    "# Update by running: python scripts/schema-drift.py --write\n"
    "# Each section is sorted to be deterministic across migration apply order.\n"
    "\n"
)

# ----------------------------------------------------------------------
# Schema introspection queries
# ----------------------------------------------------------------------
Q_TABLES = """
SELECT c.relname AS table_name,
       CASE c.relkind
           WHEN 'r' THEN 'TABLE'
           WHEN 'p' THEN 'PARTITIONED_TABLE'
           WHEN 'v' THEN 'VIEW'
           WHEN 'm' THEN 'MATERIALIZED_VIEW'
       END AS kind,
       c.relrowsecurity      AS rls_enabled,
       c.relforcerowsecurity AS rls_forced
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
 WHERE n.nspname = 'public'
   AND c.relkind IN ('r','p','v','m')
   AND c.relname NOT LIKE 'pg_%'
"""

Q_COLUMNS = """
SELECT table_name, column_name, ordinal_position,
       data_type, character_maximum_length, numeric_precision, numeric_scale,
       is_nullable, column_default
  FROM information_schema.columns
 WHERE table_schema = 'public'
"""

Q_INDEXES = """
SELECT tablename, indexname, indexdef
  FROM pg_indexes
 WHERE schemaname = 'public'
"""

Q_CONSTRAINTS = """
SELECT con.conname  AS constraint_name,
       cls.relname  AS table_name,
       con.contype  AS contype,
       pg_get_constraintdef(con.oid) AS definition
  FROM pg_constraint con
  JOIN pg_class cls       ON cls.oid = con.conrelid
  JOIN pg_namespace nsp   ON nsp.oid = cls.relnamespace
 WHERE nsp.nspname = 'public'
"""

Q_POLICIES = """
SELECT tablename, policyname, permissive, roles, cmd,
       qual::text   AS qual,
       with_check::text AS with_check
  FROM pg_policies
 WHERE schemaname = 'public'
"""

Q_SEQUENCES = """
SELECT sequence_name, data_type, start_value, increment, minimum_value, maximum_value
  FROM information_schema.sequences
 WHERE sequence_schema = 'public'
"""


# ----------------------------------------------------------------------
# Fingerprint rendering
# ----------------------------------------------------------------------
def _row_to_str(row: tuple) -> str:
    return "|".join("" if v is None else str(v) for v in row)


def render_section(title: str, rows: list[tuple]) -> str:
    out = [f"## {title} ({len(rows)} rows)\n"]
    for row in sorted(rows, key=_row_to_str):
        out.append(_row_to_str(row) + "\n")
    out.append("\n")
    return "".join(out)


def compute_fingerprint(conn) -> str:
    cur = conn.cursor()

    cur.execute(Q_PARTITION_CHILDREN)
    excluded = EXCLUDED_TABLES | {r[0] for r in cur.fetchall()}

    cur.execute(Q_TABLES)
    tables = [r for r in cur.fetchall() if r[0] not in excluded]

    cur.execute(Q_COLUMNS)
    columns = [r for r in cur.fetchall() if r[0] not in excluded]

    cur.execute(Q_INDEXES)
    indexes = [r for r in cur.fetchall() if r[0] not in excluded]

    cur.execute(Q_CONSTRAINTS)
    constraints = [r for r in cur.fetchall() if r[1] not in excluded]

    cur.execute(Q_POLICIES)
    policies = [r for r in cur.fetchall() if r[0] not in excluded]

    cur.execute(Q_SEQUENCES)
    sequences = list(cur.fetchall())

    out = [SNAPSHOT_HEADER]
    out.append(render_section("TABLES",      tables))
    out.append(render_section("COLUMNS",     columns))
    out.append(render_section("INDEXES",     indexes))
    out.append(render_section("CONSTRAINTS", constraints))
    out.append(render_section("POLICIES",    policies))
    out.append(render_section("SEQUENCES",   sequences))
    return "".join(out)


# ----------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------
def connect(url: str):
    try:
        import psycopg2  # type: ignore
    except ImportError:
        print("error: psycopg2 not installed. Run `pip install psycopg2-binary`.", file=sys.stderr)
        sys.exit(2)
    try:
        return psycopg2.connect(url)
    except Exception as e:  # noqa: BLE001 — translate to a friendly exit code
        print(f"error: cannot connect to {url}: {e}", file=sys.stderr)
        sys.exit(2)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Write fingerprint to snapshot file.")
    mode.add_argument("--check", action="store_true", help="Diff fingerprint vs committed snapshot, exit 1 on drift.")
    ap.add_argument(
        "--url",
        default=DEFAULT_PG_URL,
        help=f"PostgreSQL URL (default: {DEFAULT_PG_URL}). Also reads $DATABASE_URL.",
    )
    ap.add_argument(
        "--snapshot",
        type=Path,
        default=DEFAULT_SNAPSHOT_PATH,
        help=f"Snapshot file path (default: {DEFAULT_SNAPSHOT_PATH.relative_to(DEFAULT_SNAPSHOT_PATH.parents[2])}).",
    )
    args = ap.parse_args()

    conn = connect(args.url)
    try:
        fingerprint = compute_fingerprint(conn)
    finally:
        conn.close()

    if args.write:
        args.snapshot.parent.mkdir(parents=True, exist_ok=True)
        args.snapshot.write_text(fingerprint, encoding="utf-8")
        print(f"[OK] wrote schema fingerprint → {args.snapshot}")
        return 0

    # --check
    if not args.snapshot.exists():
        print(
            f"error: snapshot file missing at {args.snapshot}.\n"
            f"Run `python scripts/schema-drift.py --write` to bootstrap it.",
            file=sys.stderr,
        )
        return 1
    expected = args.snapshot.read_text(encoding="utf-8")
    if fingerprint == expected:
        print(f"[PASS] live schema matches snapshot ({args.snapshot.name}).")
        return 0

    diff = difflib.unified_diff(
        expected.splitlines(keepends=True),
        fingerprint.splitlines(keepends=True),
        fromfile=str(args.snapshot.name) + " (committed)",
        tofile="live (from --url)",
        n=3,
    )
    print(
        "[FAIL] schema drift detected — live DB diverges from committed snapshot.\n"
        "\n"
        "Likely cause:\n"
        "  1. Added a new migration without running `python scripts/schema-drift.py --write`.\n"
        "  2. Modified an existing migration after the snapshot was written.\n"
        "  3. Manual DDL ran outside the migration tooling.\n"
        "\n"
        "If the drift is intentional (you added a migration), regenerate the\n"
        "snapshot and commit it together with the migration:\n"
        "    python scripts/schema-drift.py --write\n"
        "    git add infrastructure/postgres/schema_snapshot.txt\n"
        "\n"
        "--- diff ---",
        file=sys.stderr,
    )
    sys.stderr.write("".join(diff))
    return 1


if __name__ == "__main__":
    sys.exit(main())
