"""Shape tests for migrations 053 + 054 — workflow builder.

053 = workflows + workflow_nodes + workflow_edges + workflow_step_documents
      + workflow_templates tables with RLS K-1 + ABAC dept_scope.
054 = auto-generated by scripts/generate_workflow_templates_migration.py —
      18 templates × ~5 cards. We verify the generator output structure
      (template count, dept coverage, card schema completeness).

Pure-Python (no DB). Pattern mirrors test_migrations_051_052_shape.py.
Run from repo root:  python -m pytest scripts/test_migrations_053_054_shape.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
MIG_DIR = REPO / "infrastructure" / "postgres" / "migrations"
sys.path.insert(0, str(REPO / "scripts"))

MIG_053_RAW = (MIG_DIR / "053_workflow_builder_tables.sql").read_text(encoding="utf-8")
MIG_054_RAW = (MIG_DIR / "054_workflow_templates_seed.sql").read_text(encoding="utf-8")


# ─── Mig 053 — table creation ───────────────────────────────────────────


EXPECTED_TABLES = [
    "workflows",
    "workflow_nodes",
    "workflow_edges",
    "workflow_step_documents",
    "workflow_templates",
]


@pytest.mark.parametrize("table", EXPECTED_TABLES)
def test_mig_053_creates_table(table):
    assert f"CREATE TABLE IF NOT EXISTS {table}" in MIG_053_RAW, (
        f"Mig 053 missing CREATE TABLE for {table}"
    )


@pytest.mark.parametrize("table", [
    "workflows", "workflow_nodes", "workflow_step_documents"
])
def test_mig_053_enterprise_scoped_table_has_enterprise_id(table):
    """Per-tenant tables must carry enterprise_id for RLS K-1."""
    idx = MIG_053_RAW.index(f"CREATE TABLE IF NOT EXISTS {table}")
    body = MIG_053_RAW[idx:idx + 5000]
    assert "enterprise_id" in body, f"{table} missing enterprise_id"


def test_mig_053_card_schema_includes_anh_fields():
    """Per anh's directive: each card needs note + hashtags +
    required_document_types + expected_mapping_template_id."""
    idx = MIG_053_RAW.index("CREATE TABLE IF NOT EXISTS workflow_nodes")
    body = MIG_053_RAW[idx:idx + 4000]
    assert "title" in body
    assert "note" in body
    assert "hashtags" in body
    assert "required_document_types" in body
    assert "expected_mapping_template_id" in body
    assert "sequence_order" in body


def test_mig_053_workflow_step_documents_links_bronze_files():
    """workflow_step_documents = the join table linking uploaded bronze
    files to workflow cards (anh's 'data lưu theo sơ đồ tree')."""
    idx = MIG_053_RAW.index("CREATE TABLE IF NOT EXISTS workflow_step_documents")
    body = MIG_053_RAW[idx:idx + 2500]
    assert "REFERENCES bronze_files" in body
    assert "REFERENCES workflows" in body
    assert "REFERENCES workflow_nodes" in body


def test_mig_053_has_k1_and_abac_policies():
    """K-1 isolation + ABAC dept_scope mirror mig 047 pattern."""
    assert "CREATE POLICY isolation_%I" in MIG_053_RAW
    assert "CREATE POLICY abac_dept_scope_%I" in MIG_053_RAW
    assert "app.current_enterprise_id" in MIG_053_RAW
    assert "app.current_department_id" in MIG_053_RAW


def test_mig_053_workflow_templates_is_global_no_rls():
    """workflow_templates is a global registry (like kpi_definitions).
    No enterprise_id, no RLS — same pattern as mig 049."""
    idx = MIG_053_RAW.index("CREATE TABLE IF NOT EXISTS workflow_templates")
    body = MIG_053_RAW[idx:MIG_053_RAW.index("-- ─── 6", idx)]
    # No enterprise_id column declaration (the table body only — checks
    # don't accidentally cross into RLS sections).
    assert "enterprise_id  UUID            NOT NULL REFERENCES" not in body


def test_mig_053_workflow_state_enum_includes_5_phase1_states():
    """Workflow state machine per docx Phần 5. Phase 1 uses these 5."""
    for state in ("DRAFT", "TESTING", "ACTIVE_BASELINE", "ARCHIVED", "BROKEN"):
        assert f"'{state}'" in MIG_053_RAW


def test_mig_053_workflow_source_enum_matches_docx():
    """source enum per docx Phần 1.1 v2.0."""
    for src in ("user_built", "template_based", "process_mining_discovered"):
        assert f"'{src}'" in MIG_053_RAW


def test_mig_053_hashtags_uses_text_array_with_gin_index():
    """Hashtags = text[] so the FE can filter '#q1_campaign' globally."""
    assert "hashtags            TEXT[]" in MIG_053_RAW
    assert "USING GIN (hashtags)" in MIG_053_RAW


def test_mig_053_self_loop_edge_blocked():
    """Workflow DAGs disallow self-loops (Build Week — Phase 2 may unlock
    for loop-style workflows with explicit guard)."""
    assert "source_node_id <> target_node_id" in MIG_053_RAW


# ─── Mig 054 — template generator output ───────────────────────────────


def test_mig_054_is_auto_generated_marker():
    """Generated SQL must self-identify so future em doesn't hand-edit."""
    assert "AUTO-GENERATED" in MIG_054_RAW
    assert "generate_workflow_templates_migration.py" in MIG_054_RAW


def test_mig_054_inserts_into_workflow_templates():
    assert "INSERT INTO workflow_templates" in MIG_054_RAW


def test_mig_054_template_count_matches_catalog():
    """Catalog says 18 templates (3 per dept × 6 depts) — VALUES rows
    must match."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    assert len(ALL_TEMPLATES) == 18

    # Count VALUES rows: each row starts with `    (` and ends with `)`.
    # Use the catalog as source of truth + verify SQL has at least N tuples.
    paren_rows = re.findall(r"\n    \('", MIG_054_RAW)
    assert len(paren_rows) == 18


def test_mig_054_covers_all_6_dept_types():
    """Per docx Phần 17.1, each dept_type must have at least 1 template."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    depts = {t.department_type for t in ALL_TEMPLATES}
    assert depts == {
        "marketing", "sales", "customer_service",
        "warehouse", "hr", "finance",
    }


def test_mig_054_three_templates_per_dept():
    """Anh's directive: 3 workflows per dept (c/d/e)."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    by_dept: dict[str, int] = {}
    for t in ALL_TEMPLATES:
        by_dept[t.department_type] = by_dept.get(t.department_type, 0) + 1
    for dept, count in by_dept.items():
        assert count == 3, f"{dept} has {count} templates (expected 3)"


def test_mig_054_every_template_has_5_cards():
    """Build Week consistency: each template = exactly 5 cards (steps)."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    for t in ALL_TEMPLATES:
        assert len(t.cards) == 5, (
            f"{t.name} ({t.department_type}) has {len(t.cards)} cards (expected 5)"
        )


def test_mig_054_every_card_has_title_and_title_vi():
    """Vietnamese SME audience — every card must have a Vietnamese title."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    for t in ALL_TEMPLATES:
        for c in t.cards:
            assert c.title and c.title_vi, (
                f"{t.name} card '{c.title}' missing title or title_vi"
            )


def test_mig_054_card_required_document_types_have_valid_shape():
    """required_documents shape locked: {kind, name, required}."""
    from generate_workflow_templates_migration import ALL_TEMPLATES  # noqa: PLC0415
    for t in ALL_TEMPLATES:
        for c in t.cards:
            for doc in c.required_documents:
                assert "kind" in doc and "name" in doc and "required" in doc, (
                    f"{t.name} card '{c.title}' malformed doc: {doc!r}"
                )


def test_mig_054_template_definition_emits_valid_jsonb():
    """Each template's workflow_definition must be parseable JSON
    with nodes[] + edges[]."""
    from generate_workflow_templates_migration import (   # noqa: PLC0415
        ALL_TEMPLATES, template_to_definition,
    )
    for t in ALL_TEMPLATES:
        wf_def = template_to_definition(t)
        assert "nodes" in wf_def and "edges" in wf_def
        assert len(wf_def["nodes"]) == 5
        assert len(wf_def["edges"]) == 4  # sequential 5 cards → 4 edges
        # Each node has client_id used by edges.
        client_ids = {n["client_id"] for n in wf_def["nodes"]}
        for e in wf_def["edges"]:
            assert e["source_client_id"] in client_ids
            assert e["target_client_id"] in client_ids


def test_mig_053_and_054_have_anh_directive_citation():
    """Both migrations cite anh's directive — paper trail."""
    assert "anh" in MIG_053_RAW.lower()
    assert "2026-05-15" in MIG_053_RAW
